// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/soap-editor/CompactGridDashboard.tsx": () => import("../components/mockups/soap-editor/CompactGridDashboard.tsx"),
  "./components/mockups/soap-editor/SidebarWorkspace.tsx": () => import("../components/mockups/soap-editor/SidebarWorkspace.tsx"),
  "./components/mockups/soap-editor/StepperWizard.tsx": () => import("../components/mockups/soap-editor/StepperWizard.tsx")
};
